version: 2.1

orbs:
  node: circleci/node@5.1.1

jobs:
  deploy:
    executor: node/default
    steps:
      - checkout

      - node/install-packages:
          pkg-manager: npm

      - run:
          name: Install Netlify CLI
          command: npm install netlify-cli -g

      - run:
          name: Link directory to Netlify site
          command: netlify link --id 77983437-c7af-42da-9609-93308643b6bb

      - run:
          name: Run tests
          command: npm run test

      - run:
          name: Build Application
          command: npm run build

      - run:
          name: Deploy to Netlify
          command: |
            netlify deploy --prod --dir=dist --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
